// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: windowmanager.proto
// Protobuf C++ Version: 6.32.1

#ifndef windowmanager_2eproto_2epb_2eh
#define windowmanager_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_windowmanager_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_windowmanager_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_windowmanager_2eproto;
}  // extern "C"
class Packet;
struct PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Packet_class_data_;
class WindowRequest;
struct WindowRequestDefaultTypeInternal;
extern WindowRequestDefaultTypeInternal _WindowRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WindowRequest_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class WindowRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:WindowRequest) */ {
 public:
  inline WindowRequest() : WindowRequest(nullptr) {}
  ~WindowRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WindowRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WindowRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WindowRequest(::google::protobuf::internal::ConstantInitialized);

  inline WindowRequest(const WindowRequest& from) : WindowRequest(nullptr, from) {}
  inline WindowRequest(WindowRequest&& from) noexcept
      : WindowRequest(nullptr, ::std::move(from)) {}
  inline WindowRequest& operator=(const WindowRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline WindowRequest& operator=(WindowRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WindowRequest& default_instance() {
    return *reinterpret_cast<const WindowRequest*>(
        &_WindowRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WindowRequest& a, WindowRequest& b) { a.Swap(&b); }
  inline void Swap(WindowRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WindowRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WindowRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WindowRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WindowRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WindowRequest& from) { WindowRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WindowRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "WindowRequest"; }

 protected:
  explicit WindowRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WindowRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WindowRequest& from);
  WindowRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WindowRequest&& from) noexcept
      : WindowRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWindowFieldNumber = 1,
  };
  // uint64 window = 1;
  void clear_window() ;
  ::uint64_t window() const;
  void set_window(::uint64_t value);

  private:
  ::uint64_t _internal_window() const;
  void _internal_set_window(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:WindowRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WindowRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t window_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_windowmanager_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WindowRequest_class_data_;
// -------------------------------------------------------------------

class Packet final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Packet) */ {
 public:
  inline Packet() : Packet(nullptr) {}
  ~Packet() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Packet* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Packet));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Packet(::google::protobuf::internal::ConstantInitialized);

  inline Packet(const Packet& from) : Packet(nullptr, from) {}
  inline Packet(Packet&& from) noexcept
      : Packet(nullptr, ::std::move(from)) {}
  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }
  inline Packet& operator=(Packet&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Packet& default_instance() {
    return *reinterpret_cast<const Packet*>(
        &_Packet_default_instance_);
  }
  enum DataCase {
    kWindowRequest = 1,
    DATA_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Packet& a, Packet& b) { a.Swap(&b); }
  inline void Swap(Packet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Packet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Packet* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Packet>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Packet& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Packet& from) { Packet::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Packet* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Packet"; }

 protected:
  explicit Packet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Packet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Packet& from);
  Packet(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Packet&& from) noexcept
      : Packet(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWindowRequestFieldNumber = 1,
  };
  // .WindowRequest window_request = 1;
  bool has_window_request() const;
  private:
  bool _internal_has_window_request() const;

  public:
  void clear_window_request() ;
  const ::WindowRequest& window_request() const;
  [[nodiscard]] ::WindowRequest* PROTOBUF_NULLABLE release_window_request();
  ::WindowRequest* PROTOBUF_NONNULL mutable_window_request();
  void set_allocated_window_request(::WindowRequest* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_window_request(::WindowRequest* PROTOBUF_NULLABLE value);
  ::WindowRequest* PROTOBUF_NULLABLE unsafe_arena_release_window_request();

  private:
  const ::WindowRequest& _internal_window_request() const;
  ::WindowRequest* PROTOBUF_NONNULL _internal_mutable_window_request();

  public:
  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:Packet)
 private:
  class _Internal;
  void set_has_window_request();
  inline bool has_data() const;
  inline void clear_has_data();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Packet& from_msg);
    union DataUnion {
      constexpr DataUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::WindowRequest* PROTOBUF_NULLABLE window_request_;
    } data_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_windowmanager_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Packet_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WindowRequest

// uint64 window = 1;
inline void WindowRequest::clear_window() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.window_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t WindowRequest::window() const {
  // @@protoc_insertion_point(field_get:WindowRequest.window)
  return _internal_window();
}
inline void WindowRequest::set_window(::uint64_t value) {
  _internal_set_window(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:WindowRequest.window)
}
inline ::uint64_t WindowRequest::_internal_window() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.window_;
}
inline void WindowRequest::_internal_set_window(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.window_ = value;
}

// -------------------------------------------------------------------

// Packet

// .WindowRequest window_request = 1;
inline bool Packet::has_window_request() const {
  return data_case() == kWindowRequest;
}
inline bool Packet::_internal_has_window_request() const {
  return data_case() == kWindowRequest;
}
inline void Packet::set_has_window_request() {
  _impl_._oneof_case_[0] = kWindowRequest;
}
inline void Packet::clear_window_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (data_case() == kWindowRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.data_.window_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.data_.window_request_);
    }
    clear_has_data();
  }
}
inline ::WindowRequest* PROTOBUF_NULLABLE Packet::release_window_request() {
  // @@protoc_insertion_point(field_release:Packet.window_request)
  if (data_case() == kWindowRequest) {
    clear_has_data();
    auto* temp = _impl_.data_.window_request_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.data_.window_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::WindowRequest& Packet::_internal_window_request() const {
  return data_case() == kWindowRequest ? *_impl_.data_.window_request_ : reinterpret_cast<::WindowRequest&>(::_WindowRequest_default_instance_);
}
inline const ::WindowRequest& Packet::window_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Packet.window_request)
  return _internal_window_request();
}
inline ::WindowRequest* PROTOBUF_NULLABLE Packet::unsafe_arena_release_window_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Packet.window_request)
  if (data_case() == kWindowRequest) {
    clear_has_data();
    auto* temp = _impl_.data_.window_request_;
    _impl_.data_.window_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Packet::unsafe_arena_set_allocated_window_request(
    ::WindowRequest* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_data();
  if (value) {
    set_has_window_request();
    _impl_.data_.window_request_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Packet.window_request)
}
inline ::WindowRequest* PROTOBUF_NONNULL Packet::_internal_mutable_window_request() {
  if (data_case() != kWindowRequest) {
    clear_data();
    set_has_window_request();
    _impl_.data_.window_request_ = 
        ::google::protobuf::Message::DefaultConstruct<::WindowRequest>(GetArena());
  }
  return _impl_.data_.window_request_;
}
inline ::WindowRequest* PROTOBUF_NONNULL Packet::mutable_window_request()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::WindowRequest* _msg = _internal_mutable_window_request();
  // @@protoc_insertion_point(field_mutable:Packet.window_request)
  return _msg;
}

inline bool Packet::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void Packet::clear_has_data() {
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}
inline Packet::DataCase Packet::data_case() const {
  return Packet::DataCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // windowmanager_2eproto_2epb_2eh
